config/routes.rb
Rails.application.routes.draw do
  resources :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	
	before_action :set_tweet, only: [:show, :edit, :update, :destroy]

	def index
		@tweets = Tweet.all
	end	

	def show
	end	

	def new
		@tweet = Tweet.new
	end	

	def edit
	end	

	def create
		@tweet = Tweet.new(tweet_params)	

		if @tweet.save
			redirect_to tweets_path
		else
			render :new
		end
	end	

	def update
		if @tweet.update_attributes(tweet_params)
			redirect_to tweets_path
		else
			render :edit
		end
	end	

	def destroy
		@tweet.destroy
		redirect_to tweets_path
	end	

	private
	def set_tweet
		@tweet = Tweet.find(params[:id])
	end	
	
	def tweet_params
		params.require(:tweet).permit(:handle, :content)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitter</title>
  <%= stylesheet_link_tag 'application', media:'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>

<header>
	<div class="ProfileAvatar">
		<img class="ProfileAvatarImg" src="http://is4.mzstatic.com/image/thumb/Purple49/v4/7f/03/0c/7f030ca7-449f-e70d-cf09-cf1a4e4d00b1/source/0x0ss-85.png">
	</div>
</header>

<body>
	<nav class="navbar navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="https://twitter.com/">
	      	<img src="https://upload.wikimedia.org/wikipedia/en/archive/9/9f/20161107041729!Twitter_bird_logo_2012.svg" width="23" height="21"></a>
	    </div>
	      <ul class="nav navbar-nav home-nav">
	        <li id="home"><a href="#">Home</a></li>
	        <li><a href="#">Moments</a></li>
	        	



	        	  
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	      	<li><a href="#">Have an account? Log in</a></li>
	      </ul>
	      <form class="navbar-form navbar-right">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search Twitter">
	        </div>
	      </form>
	  </div>
	</nav>

	

<div class="container-fluid">
	<div class="row container-fluid" id="navbar2">
	  <div class="col-md-3 sidebar-left"></div>
	  <div class="col-md-6">
	  	<div class="tweet-stream">
		  	<nav class="navbar2">
		  	    <ul class="nav navbar-nav">
		  	      <li><a class="tweet-stats" href="#">Tweets</a><span class="tweet-values">496</span></li>
		  	      <li><a class="tweet-stats" href="#">Following</a><span class="tweet-values">4,053</span></li>
		  	      <li><a class="tweet-stats" href="#">Followers</a><span class="tweet-values">6.26M</span></li>
		  	      <li><a class="tweet-stats" href="#">Likes</a><span class="tweet-values">3,042</span></li>
		  	    </ul>
		  	</nav>
	  	</div>
	  </div>
	  <div class="col-md-3 sidebar"></div>
	</div>
 	<div class="row app-content">
 	  <div class="col-md-3 sidebar">
 	  	<div class="sidebar-left">
 	  		<p class="name">Gudetama_Fanpage <img alt="Verified account" src="https://www.tripepismith.com/wp-content/uploads/2015/06/Twitter-checkmark.png" width="17.5" height="18"></p>
 	  		<p>@gudetama</p>
 	  		<p class="profile-info">毎日つぶやくのめんどくさい。だるい。エラい人がやれっていうからやるけど、どーせ食われるだけだし。 サンリオのソーシャルメディアポリシ</p>
 	  	</div>
 	  </div>
 	  <div class="col-md-6">
 	  	<div class="tweet-stream">
	 	  	<nav class="navbar3">
	 	  	    <ul class="nav navbar-nav">
	 	  	      <li><a href="#" data-toggle="modal" data-target="#myModal">Tweets</a></li>
	 	  	      <li><a href="#">Tweets &amp; replies</a></li>
	 	  	      <li><a href="#">Media</a></li>
	 	  	    </ul>
	 	  	</nav>
	 	  	<%= yield %>
 	  	</div>
 	  </div>
 	  <div class="col-md-3 sidebar">
 	  	<div class="SignUp">
 	  		<h3>New to Twitter?</h3>
 	  		<p>Sign up now and get your own personalized timeline!</p>
 	  		<button type="button" class="btn btn-default btn-block">Sign up</button>
 	  	</div>
 	  	<div class="sidebar-right">You may also like</div>
 	  	<div class="sidebar-right">Worldwide Trends</div>
 	  </div>
 	</div>
</div>

<!-- Modal -->
<!--<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog">

    	Modal content
    	<div class="modal-content">
    	  <div class="modal-header">
    	    <button type="button" class="close" data-dismiss="modal">&times;</button>
    	    <h4 class="modal-title">This link does not work</h4>
    	  </div>
    	  <div class="modal-body">
    	    <p>Some text in the modal.</p>
    	  </div>
    	  <div class="modal-footer">
    	    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    	  </div>
    	</div>
	</div>
</div> 
-->

</body>

</html>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= form_for @tweet do |f| %>

    <div>
        <%= f.label :handle %>
        <%= f.text_field :handle %>
    </div>

    <div>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", tweets_path %>

app/views/tweets/index.html.erb
<div class="panel">
	<% @tweets.each do |tweet| %>

  <div class="panel-heading">
  	<strong>Gudetama_Fanpage</strong> &#64;<%= tweet.handle %>
    <%= time_ago_in_words(tweet.created_at.localtime) + " ago" %>
  </div>
  <div class="panel-body">
    <div class="panel-body-text">
      <%= tweet.content %><br>
      <%= link_to "View Tweet", tweet_path(tweet) %>
    </div>
  </div>
  <% end %>
</div>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>Add a tweet!</h1>

<%= form_for @tweet do |f| %>

    <div>
        <%= f.label :handle %>
        <%= f.text_field :handle %>
    </div>

    <div>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </div>

    <%= f.submit "Add new tweet!" %>

<% end %>

<%= link_to "Back", tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>Handle:</strong>
  <%= @tweet.handle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= @tweet.created_at.localtime.strftime("%I:%M%p %b %d %Y") %><br>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> 
<%= link_to "Delete this tweet!", tweet_path, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?"} %>
<%= link_to 'Back', tweets_path %>